name: Build

run-name: Build Code

on:
  push:
    branches: ['main']

permissions:
  contents: write

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - run: touch .nojekyll

      - name: Minify Code
        uses: Lenni009/minify-js@main
        with:
          overwrite: true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # The folder the action should deploy.
